### ISSUE TITLE
error with CRC module when upgrading from 1.12.1

### ISSUE THREAD

**Issue by franckl** [expressjs/session#267]
I am using node 0.10 (through openshift online) and I got the following error when I upgraded express-session. 
Any idea why ?

```
Error: Cannot find module './define_crc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/openshift/54d0254bfcf9332adf0000a6/app-root/runtime/repo/node_modules/express-session/node_modules/crc/lib/crc1.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
DEBUG: Program node server.js exited with code 8
DEBUG: Starting child process with 'node server.js'
module.js:340
    throw err;
          ^
```

**Comment by dougwilson** [comment]
Hi @franckl, I have no idea why that would happen. Our tests on Travis CI are working just fine. Is it possible you are running some kind of transformer on your `node_modules` directory (like Webpack or browserify, for example)? Another option is trying to destroy any cached npm modules and try re-installing. For example, running in the same session would would run `npm installed` in, run `npm cache clean` first.

**Comment by dougwilson** [comment]
Hi @franckl, I'm going to close this since I haven't heard back and cannot seem to reproduce. Please feel free to provide more details here and I can always re-open!

**Comment by franckl** [comment]
Hi! Sorry for the late reply. I had to revert the upgrade to the previous
state and was not able to reproduce it again...
