### ISSUE TITLE
1.8.0: 'save' failing when wrapped methods are in session

### ISSUE THREAD

**Issue by pmanijak** [expressjs/session#85]
Hey, just a heads up, I'm seeing this the second time a page is hit (at the end of a response):

```
TypeError: Object function save() {
        debug('saving %s', this.id);
        savedHash = hash(this);
        _save.apply(this, arguments);
      } has no method 'apply'
    at Session.save (~\node_modules\express-session\index.js:292:15)
    at ServerResponse.end (~\node_modules\express-session\index.js:264:21)
    at ServerResponse.send (~\node_modules\express\lib\response.js:191:8)
    at fn (~\node_modules\express\lib\response.js:951:10)
```

I'm seeing the issue with a custom session store that works fine with 1.7.6. It does not implement 'resave' or 'saveUninitialized'. Here is [the source for that](https://github.com/corvallisswing/swingandblues.org/blob/master/routes/lib/couch-session-store.js).

This is what's in the session object at the time of failure:

```
{
   "cookie": {
       "originalMaxAge": 1209600000,
       "expires": "2014-09-22T17:56:16.803Z",
       "secure": false,
       "httpOnly": true,
       "path": "/"
   },
   "save": "function save() {\n        debug('saving %s', this.id);\n        savedHash = hash(this);\n        _save.apply(this, arguments);\n      }",
   "passport": {
   }
}
```

I just thought I'd log this now since the 1.8 release is new. I can dig into this later this week.
